### ISSUE TITLE
Learning TaskList

### ISSUE THREAD

**Issue by LYyI** [LYyI/git-tutorial-re#2]
# Task of April
- [x] complete the painting
- [x] finish the settings of tomcat and niginx
- [x] bring about the random function
